version: '3'

services:
    with-docker-multi-env-development:
        build:
            context: ../../
            dockerfile: docker/development/Dockerfile
        image: with-docker-multi-env-development
        ports:
            - '3000:3000'
        volumes:
            - ../../:/app
            - ../../node_modules:/node_modules
            - ../../.next:/app/.next
        depends_on:
            - mongo-dev

    mongo-dev:
        restart: always
        image: mongo:7.0.2
        volumes:
            - ./data:/data/db
        networks:
            - express-mongo
        expose:
            - 27017
networks:
    express-mongo:
