version: '3'

services:
    github-dependencies-app-dev:
        build:
            context: ../../
            dockerfile: docker/development/Dockerfile
        image: github-dependencies-app-dev
        ports:
            - '3000:3000'
        volumes:
            - ../../:/app
            - ../../node_modules:/node_modules
            - ../../.next:/app/.next
        depends_on:
            - github-dependencies-db-dev

    github-dependencies-db-dev:
        restart: always
        image: mongo:7.0.2
        volumes:
            - ./data:/data/db
        networks:
            - express-mongo
        ports:
            - '27017:27017'
        expose:
            - '27017:27017'
networks:
    express-mongo:
