services:
    frontend:
        build:
            context: ./src/frontend
            target: development
        ports:
            - 3000:3000
        stdin_open: true
        volumes:
            - ./src/frontend:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
        networks:
            - react-express
        depends_on:
            - backend

    backend:
        restart: always
        build:
            context: ./src/backend
            target: development
        volumes:
            - ./src/backend:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - mongo
        networks:
            - express-mongo
            - react-express
        expose:
            - 3000
    mongo:
        restart: always
        image: mongo:4.2.0
        volumes:
            - ./data:/data/db
        networks:
            - express-mongo
        expose:
            - 27017
networks:
    react-express:
    express-mongo:
